name: meme_soundpad
description: "A simple Meme SoundPad app built in flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.14
  just_audio: ^0.9.34
  search_page: ^2.3.0
  firebase_core: ^3.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
